[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[dev]
  command = "npm run dev"
  targetPort = 8080
  autoLaunch = false
