name = "conversion-boost-sbelta"
type = "javascript"
main = "dist/server/server.js"
compatibility_date = "2024-01-01"

[env.production]
name = "conversion-boost-sbelta-prod"
route = "conversion-boost-sbelta.gloria-ponguta08.workers.dev/*"
zone_id = ""
account_id = ""
